inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - test/dummy/db/schema.rb
    - test/dummy/bin/**/*
    - app/helpers/solid_queue_panel/icons_helper.rb
